View(food)
hist(food$calories_chicken)
hist(food$calories_chicken, main = "Number of Calories Each Student Gets From Chicken", ylab = "Number of Students", xlab = "Number of Calories")
hist(food$eating_out)
hist(food$eating_out, main = "Number of Times Students That Eat Out", xlab = "Eating Outside Food", ylab = "Number of Students")
hist(food$exercise)
hist(food$eating_out, main = "Number of Times That Students Eat Out", xlab = "Eating Outside Food", ylab = "Number of Students")
hist(food$grade_level)
hist(food$grade_level, main = "The Grade Level of Each Student", xlab = "Grade Level", ylab = "Number of Students")
hist(food$healthy_feeling, main = "Rating on How Healthy Each Student Feels", xlab = " Rating (From 1-10)", ylab = "Number of Students")
